# Generated by Django 5.2.6 on 2025-09-29 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='expensa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('pagada', models.BooleanField(default=False)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('descripcion', models.CharField(default='Expensa de condominio', max_length=255)),
            ],
            options={
                'verbose_name': 'Expensa',
                'verbose_name_plural': 'Expensas',
                'db_table': 'expensa',
            },
        ),
        migrations.CreateModel(
            name='multa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_multa', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('I', 'Incidente'), ('F', 'falta de pago'), ('O', 'otros')], default='I', max_length=1)),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': 'multa',
            },
        ),
        migrations.CreateModel(
            name='contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField()),
                ('cuota_mensual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('P', 'Pendiente'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('costo_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('contrato_PDF', models.URLField(blank=True, null=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_propietario', to='administracion.persona')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
            },
        ),
    ]
