# Generated by Django 5.2.6 on 2025-09-29 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('residencial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_unidad', to='residencial.unidad'),
        ),
        migrations.AddField(
            model_name='expensa',
            name='unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expensas_unidad', to='residencial.unidad'),
        ),
        migrations.AddField(
            model_name='multa',
            name='expensa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multas_expensa', to='finanzas.expensa'),
        ),
    ]
