# Generated by Django 5.2.6 on 2025-09-29 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del Bloque')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
            ],
            options={
                'verbose_name': 'Bloque',
                'verbose_name_plural': 'Bloques',
                'db_table': 'bloque',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('motivo_visita', models.CharField(choices=[('FAMILIA', 'Visita Familiar'), ('TRABAJO', 'Trabajo'), ('SERVICIO', 'Servicio'), ('SOCIAL', 'Social'), ('OTRO', 'Otro')], default='FAMILIA', max_length=10, verbose_name='Motivo de Visita')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitante',
                'ordering': ['-fecha_registro'],
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HIJO', 'Hijo'), ('HIJA', 'Hija'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('ESPOSO', 'Esposo'), ('ESPOSA', 'Esposa')], max_length=10, verbose_name='Parentesco')),
                ('persona_relacionada', models.ForeignKey(limit_choices_to={'tipo__in': ['P', 'I']}, on_delete=django.db.models.deletion.CASCADE, related_name='familiares_de', to='administracion.persona', verbose_name='Persona Relacionada')),
            ],
            options={
                'verbose_name': 'Familiar',
                'verbose_name_plural': 'Familiares',
                'db_table': 'familiares',
                'ordering': ['-fecha_registro'],
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='incidente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('fecha_incidente', models.DateTimeField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('multa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_multa', to='finanzas.multa')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentes_propietario', to='administracion.persona')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'db_table': 'incidente',
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.persona')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('estado_inquilino', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('F', 'Finalizado')], default='A', max_length=1, verbose_name='Estado del Inquilino')),
                ('propietario', models.ForeignKey(limit_choices_to={'tipo': 'P'}, on_delete=django.db.models.deletion.CASCADE, related_name='inquilinos_propietario', to='administracion.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
                'db_table': 'inquilino',
                'ordering': ['-fecha_registro'],
            },
            bases=('administracion.persona',),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], default='PERRO', max_length=10, verbose_name='Especie')),
                ('tipo', models.CharField(choices=[('MACHO', 'Macho'), ('HEMBRA', 'Hembra')], default='MACHO', max_length=10, verbose_name='Tipo')),
                ('foto', models.URLField(blank=True, null=True, verbose_name='Foto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Mascota')),
                ('raza', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='administracion.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascota',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=20, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=20, verbose_name='Placa')),
                ('tipo', models.CharField(choices=[('Automóvil', 'Automóvil'), ('Camioneta', 'Camioneta'), ('SUV', 'SUV'), ('Motocicleta', 'Motocicleta'), ('Furgoneta', 'Furgoneta'), ('Crossover', 'Crossover')], max_length=20, verbose_name='Tipo')),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.persona', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'db_table': 'vehiculo',
                'ordering': ['marca', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Visita')),
                ('fecha_hora_entrada', models.DateTimeField(verbose_name='Fecha y Hora de Entrada')),
                ('fecha_hora_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Salida')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('recibe_persona', models.ForeignKey(limit_choices_to=models.Q(('tipo', 'P'), ('tipo', 'I'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='visitas_recibidas', to='administracion.persona', verbose_name='Persona que Recibe')),
                ('visitante', models.ForeignKey(limit_choices_to={'tipo': 'V'}, on_delete=django.db.models.deletion.CASCADE, related_name='visitas_realizadas', to='administracion.persona', verbose_name='Visitante')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'db_table': 'visita',
                'ordering': ['-fecha_hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10, verbose_name='Número de Unidad')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Unidad')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='Imagen')),
                ('dimensiones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensiones')),
                ('tipo_unidad', models.CharField(choices=[('A', 'Apartamento'), ('C', 'Casa'), ('L', 'Local Comercial'), ('E', 'Estacionamiento')], default='A', max_length=1, verbose_name='Tipo de Unidad')),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('O', 'Ocupada'), ('M', 'En Mantenimiento'), ('R', 'Reservada')], default='D', max_length=1, verbose_name='Estado')),
                ('numero_piso', models.PositiveIntegerField(default=1, verbose_name='Número de Piso')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Área en m²')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residencial.bloque', verbose_name='Bloque')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidad',
                'ordering': ['bloque', 'numero_piso', 'numero'],
                'unique_together': {('bloque', 'numero')},
            },
        ),
    ]
