# Generated by Django 5.2.6 on 2025-12-08 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_empleado_user_persona_user'),
        ('residencial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoPerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Qué es')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Detalles')),
                ('foto', models.URLField(verbose_name='Foto del objeto')),
                ('lugar_encontrado', models.CharField(default='Áreas Comunes', max_length=100)),
                ('fecha_encontrado', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('P', 'Pendiente de reclamo'), ('E', 'Entregado/Devuelto')], default='P', max_length=1)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('entregado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_reclamados', to='administracion.persona')),
            ],
            options={
                'verbose_name': 'Objeto Perdido',
                'verbose_name_plural': 'Objetos Perdidos',
                'ordering': ['-fecha_encontrado'],
            },
        ),
    ]
