# Generated by Django 5.2.6 on 2025-12-14 23:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_empleado_user_persona_user'),
        ('residencial', '0002_objetoperdido'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreasComunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación dentro del residencial')),
                ('capacidad_maxima', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidad Máxima')),
                ('horario_apertura', models.TimeField(verbose_name='Horario de Apertura')),
                ('horario_cierre', models.TimeField(verbose_name='Horario de Cierre')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado del Área')),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaAreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de la Reserva')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Reserva')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='residencial.areascomunes', verbose_name='Área Común')),
                ('persona', models.ForeignKey(limit_choices_to=models.Q(('tipo', 'P'), ('tipo', 'I'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='reservas_area_comun', to='administracion.persona', verbose_name='Persona que Reserva')),
            ],
            options={
                'verbose_name': 'Reserva de Área Común',
                'verbose_name_plural': 'Reservas de Áreas Comunes',
                'db_table': 'reserva_area_comun',
                'ordering': ['-fecha_reserva', '-hora_inicio'],
            },
        ),
    ]
