# Generated by Django 5.2.6 on 2025-09-27 20:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Cargo')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salario Base')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='Imagen')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1, verbose_name='Estado')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('tipo', models.CharField(choices=[('P', 'Propietario'), ('I', 'Inquilino'), ('F', 'Familiar'), ('V', 'Visitante')], max_length=1, verbose_name='Tipo de Persona')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('CI', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('CI', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('fecha_nacimiento', models.DateField(default='1990-01-01', verbose_name='Fecha de Nacimiento')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('S', 'Suspendido')], default='A', max_length=1, verbose_name='Estado')),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sueldo')),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
