# Generated by Django 5.2.6 on 2025-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='luxand_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='luxand_uuid',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
