# Generated by Django 5.2.6 on 2025-09-29 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residencial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturaPlaca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=20)),
                ('score', models.FloatField()),
                ('camera_id', models.CharField(blank=True, max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('match', models.BooleanField(default=False)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residencial.vehiculo')),
            ],
            options={
                'db_table': 'lectura_placa',
                'ordering': ['-created_at'],
            },
        ),
    ]
